5.times do
  Listing.create({user_id: hosts[0].id, title: "Listing Available in Earle, AR", description: "Meat Eater chronicles Rinella’s lifelong relationship with nature and hunting through the lens of ten hunts, beginning when he was an aspiring mountain man at age ten and ending as a thirty-seven-year-old Brooklyn father who hunts in the remotest corners of North America. He tells of having a struggling career as a fur trapper just as fur prices were falling; of a dalliance with catch-and-release steelhead fishing; of canoeing in the Missouri Breaks in search of mule deer just as the Missouri River was freezing up one November; and of hunting the elusive Dall sheep in the glaciated mountains of Alaska. Through each story, Rinella grapples with themes such as the role of the hunter in shaping America, the vanishing frontier, the ethics of killing, the allure of hunting trophies, the responsibilities that human predators have to their prey, and the disappearance of the hunter himself as Americans lose their connection with the way their food finds its way to their tables. Hunting, he argues, is intimately connected with our humanity; assuming responsibility for acquiring the meat that we eat, rather than entrusting it to proxy executioners, processors, packagers, and distributors, is one of the most respectful and exhilarating things a meat eater can do.", address: "752 State Hwy 306, Earle, AR 72331, USA", availability: "Available every weekend in the 2021-22 season.", price: "$300/weekend without a guide, $600/weekend with a guide. Sorry, but we cannot lease individual days"})
end

5.times do
  Listing.create({user_id: hosts[1].id, title: "Listing Available in Parkin, AR", description: "I grew up in Twin Lake, Michigan, the son of a hunter who taught his three sons to love the natural world the way he did. As a child, Rinella devoured stories of the American wilderness, especially the exploits of his hero, Daniel Boone. He began fishing at the age of three and shot his first squirrel at eight and his first deer at thirteen. He chose the colleges he went to by their proximity to good hunting ground, and he experimented with living solely off wild meat. As an adult, he feeds his family from the food he hunts. Meat Eater chronicles Rinella’s lifelong relationship with nature and hunting through the lens of ten hunts, beginning when he was an aspiring mountain man at age ten and ending as a thirty-seven-year-old Brooklyn father who hunts in the remotest corners of North America. He tells of having a struggling career as a fur trapper just as fur prices were falling; of a dalliance with catch-and-release steelhead fishing; of canoeing in the Missouri Breaks in search of mule deer just as the Missouri River was freezing up one November; and of hunting the elusive Dall sheep in the glaciated mountains of Alaska.", address: "647 Co Rd 806, Parkin, AR 72373, USA", availability: Faker::Date.between(from: '2021-11-26', to: '2022-01-31'), price: "150/day without a guide, $250/day with a guide."})
end

5.times do
  Listing.create({user_id: hosts[2].id, title: "Lease Available in Ripley, TN", description: "This volume has something for everyone who hunts, be they rabbit hunters in the deep South, Cape buffalo hunters in the African bush, or white-tailed deer hunters in the woods of North America. Its selections celebrate hunting for big game, small game, waterfowl, upland birds, turkeys, African and Asian game, and much more. Readers will find many of their favorite writers represented here, along with authors who have penned inspired pieces that few have read, until now. The book has been put together in keeping with the spirit and philosophy of Theodore Roosevelt, our twenty-sixth president, who not only believed in the preservation of our wildlife and natural resources, but in the importance of hunting to the fabric of American life. Part of the proceeds from this book will go to the Theodore Roosevelt Conservation Partnership, a coalition of organizations and individual grassroots partners working together to preserve the traditions of hunting and fishing.", address: "3155 Dee Webb Rd Ripley, TN 38063", availability: "This lease is available all season, 11/26/21 - 1/21/22", price: "$11,000 for the whole season"})
end

5.times do
  Listing.create({user_id: hosts[3].id, title: "Listing Available in Parkin, AR", description: "Even among the mighty mountain men, Jim Bridger was a towering figure. He was one of the greatest explorers and pathfinders in American history. He couldn't write his name, but at eighteen he had braved the fury of the Missouri, ascending it in a keelboat flotilla commanded by that stalwart Mike Fink. By 1824, when he was only twenty, he had discovered the Great Salt Lake. Later he was to open the Overland Route, which was the path of the Overland Stage, the Pony Express, and the Union Pacific. One of the foremost trappers in the Rocky Mountain Fur Company, he was a legend in his own time as well as ours. He remains one of the most important scouts and guides in the history of the West.The Christian Science Monitor has called this biography 'probably the fairest portrait of Jim Bridger in existence.' The New York Times has praise for a 'painstaking job of research among the usual Bridger sources and among some others which have been neglected. . . . [The author] has adequately set the scene for his hero's adventures and has honestly appraised the great guide's historical stature.' Other Bison Books by Stanley Vestal: Dodge City: Queen of Cowtowns, Joe Meek: The Merry MOuntain Man; The Missouri, The Old Santa Fe Trail, and Warpath: The True Story of the Fighting Sioux Told in a Biography of Chief White Bull", availability: Faker::Date.between(from: '2021-11-26', to: '2022-01-31'), price: "150/day without a guide, $250/day with a guide."})
end