# Image.create!([
#   {listing_id: 1, url: "https://images.squarespace-cdn.com/content/v1/533b0402e4b00b17bef36c51/1410818881149-I9I8MK648RHYT0QFON8J/ke17ZwdGBToddI8pDm48kOP4k6nJKwU86sL92UkQqe5Zw-zPPgdn4jUwVcJE1ZvWQUxwkmyExglNqGp0IvTJZamWLI2zvYWH8K3-s_4yszcp2ryTI0HqTOaaUohrI8PIo5fmh4JP_kiV1wIZN080qp3QoXl2SfsMhkQGk2guP8IKMshLAGzx4R3EDFOm1kBS/141754491-L-3.jpg"},
#   {listing_id: 1, url: "https://www.louisianasportsman.com/wp-content/uploads/2014/01/p1391188684-1.jpg"},
#   {listing_id: 2, url: "https://content.osgnetworks.tv/wildfowl/content/photos/mallard-drake-landing-on-water.jpg"},
#   {listing_id: 2, url: "https://mossyoak-cezjaqp1wr.netdna-ssl.com/sites/default/files/inline-images/Duck%20Hunt_0.jpg"},
#   {listing_id: 3, url: "http://mdwfp.com/media/257858/duck-hunter.jpg"},
#   {listing_id: 3, url: "https://www.outdoorproperties.com/wp-content/uploads/2014/03/1110.jpg"},
#   {listing_id: 4, url: "https://d138cv3no7lm06.cloudfront.net/sites/default/files/inline-images/DuckHuntingMississippieDelta_1.jpg"},
#   {listing_id: 4, url: "https://www.mdwfp.com/media/254344/ducks-1.jpg?width=500&height=374.2857142857143"},
#   {listing_id: 5, url: "https://lh3.googleusercontent.com/proxy/cpYSTcNtbRWo9639oYdaCl_NQIeVHh2HQoK12MSOo9XDSjmMNIkDfg8rG-jLTxN1w2MIrcXefX8XN5A5nswpFA9qZeEUELfiO1MZ0Y2AYlzpr38xDm8jdRdq-w"},
#   {listing_id: 5, url: "https://sportsmanslifestyle.com/wp-content/uploads/2017/08/Ducks_over_the_Delta.jpg"}
# ])
# Listing.create!([
#   {user_id: 2, title: "Full Season Lease Available in Earle, AR", description: "Tempus imperdiet nulla malesuada pellentesque. Nec tincidunt praesent semper feugiat. Non nisi est sit amet facilisis magna etiam tempor orci. Proin nibh nisl condimentum id venenatis. Tristique senectus et netus et malesuada fames. Cursus eget nunc scelerisque viverra mauris in aliquam sem fringilla.", address: "201 Twist HWY, Three Forks, AR 72331", latitude: 35.33862, longitude: -90.449976, availability: "Sept 15-30, Nov 21-30, Dec 11-23, 2021, Dec 26, 2021 - Jan 31, 2022", price: "$8000, one field, no splitting the leases between multiple groups"},
#   {user_id: 1, title: "Guided Weekend Hunts Available in Parkin, AR", description: "Tempus imperdiet nulla malesuada pellentesque. Nec tincidunt praesent semper feugiat. Non nisi est sit amet facilisis magna etiam tempor orci. Proin nibh nisl condimentum id venenatis. Tristique senectus et netus et malesuada fames. Cursus eget nunc scelerisque viverra mauris in aliquam sem fringilla.", address: "300 County Road 424, Togo, AR", latitude: 35.3404494, longitude: -90.5700117, availability: "Saturday/Sunday during the entire legal hunting season & juvenile hunt. No early teal.", price: "$250/day/hunter. $425 for both Saturday and Sunday together"},
#   {user_id: 1, title: "Early Season Week With Guide Available in Cherry Valley, AR", description: "Tempus imperdiet nulla malesuada pellentesque. Nec tincidunt praesent semper feugiat. Non nisi est sit amet facilisis magna etiam tempor orci. Proin nibh nisl condimentum id venenatis. Tristique senectus et netus et malesuada fames. Cursus eget nunc scelerisque viverra mauris in aliquam sem fringilla.", address: "3509 AR-1, Cherry Valley, AR 72324", latitude: 35.39853, longitude: -90.7644254, availability: "December 11 - 18, 2021", price: "With guide (available on weekends): $1800/week, without guide: $1200"},
#   {user_id: 1, title: "One week lease available in Luxora, AR", description: "Tincidunt tortor aliquam nulla facilisi cras. Urna et pharetra pharetra massa massa ultricies mi quis. Adipiscing enim eu turpis egestas pretium aenean pharetra. Morbi tristique senectus et netus et malesuada fames ac turpis. Id faucibus nisl tincidunt eget nullam non nisi est sit. Sit amet tellus cras adipiscing enim eu turpis. At augue eget arcu dictum varius duis at consectetur lorem. Adipiscing vitae proin sagittis nisl rhoncus mattis. Mauris vitae ultricies leo integer malesuada nunc vel. Nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Vulputate enim nulla aliquet porttitor lacus luctus. Amet risus nullam eget felis eget nunc lobortis.", address: "2908 E Co Rd 570, Luxora, AR 72358", latitude: 35.763034, longitude: -89.909557, availability: "December 12-18, 2021", price: "$1050"},
#   {user_id: 1, title: "LEASE AVAILABLE", description: "asdf;lkajsdf;lkajsdf;lkasjdf;lkj", address: "3541 E State Hwy 120, Luxora, AR", latitude: 35.783921, longitude: -89.88091, availability: nil, price: nil},
#   {user_id: 2, title: "Two weekends Available in Parkin, AR", description: "Tempus imperdiet nulla malesuada pellentesque. Nec tincidunt praesent semper feugiat. Non nisi est sit amet facilisis magna etiam tempor orci. Proin nibh nisl condimentum id venenatis. Tristique senectus et netus et malesuada fames. Cursus eget nunc scelerisque viverra mauris in aliquam sem fringilla.", address: "1100, AR 306, Gieseck, Arkansas, 72373", latitude: 35.17955, longitude: -90.583903, availability: "Dec 11-12, 2021, Jan 1-3, 2022", price: "$450/per weekend, sorry, individual days are not available."}
# ])
# User.create!([
#   {first_name: "William", last_name: "Petty", email: "pettwil1131@gmail.com", phone_number: "5555555555", address: "1131 Harbor River Cv", city: "Memphis", state: "TN", about_me: "Hey I'm Will. I live in Memphis, TN and I enjoy duck hunting, fishing, golf, and gardening.", image_url: "https://avatars.githubusercontent.com/u/77342332?v=4", host: true, password_digest: "$2a$12$1yZn7qRoOFY8/l3FASrH/OkMa7SSO8tHiiWGbbIjZcLtMhLSz4HUK", zip_code: "38103"},
#   {first_name: "Bill", last_name: "Shelby", email: "bill@gmail.com", phone_number: "5555555555", address: "1900 York Ave", city: "Memphis", state: "TN", about_me: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ipsum suspendisse ultrices gravida dictum. Vestibulum morbi blandit cursus risus at ultrices. Bibendum at varius vel pharetra vel turpis nunc eget. Ornare arcu dui vivamus arcu felis bibendum ut tristique et.", image_url: "https://www.fillmurray.com/640/360", host: true, password_digest: "$2a$12$6.xyvMR6tZzBq.EdL82IgeKPhD7ysdNa06AVlKDe.UTArt9VH4Cai", zip_code: "38104"},
#   {first_name: "Evan", last_name: "Mallard", email: "evan@gmail.com", phone_number: "5555555555", address: "1154 Harbor River Cv", city: "Memphis", state: "TN", about_me: "Etiam sit amet nisl purus in mollis nunc sed id. Aenean euismod elementum nisi quis eleifend quam. Dolor morbi non arcu risus quis. Montes nascetur ridiculus mus mauris vitae ultricies leo. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Volutpat ac tincidunt vitae semper quis lectus.", image_url: "https://www.stevensegallery.com/640/360", host: false, password_digest: "$2a$12$ZPbry9HHyZRb8FunqAxKBOQnAMqfNvMcnrU33px249yrS3xQ2BhTG", zip_code: "38103"},
#   {first_name: "Bentley", last_name: "Teal", email: "bentley@gmail.com", phone_number: "5555555555", address: "1123 Harbor Bend Cv", city: "Memphis", state: "TN", about_me: "In aliquam sem fringilla ut morbi tincidunt augue interdum velit. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Duis ultricies lacus sed turpis tincidunt id. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Massa tempor nec feugiat nisl pretium fusce.", image_url: "https://www.placecage.com/640/360", host: false, password_digest: "$2a$12$vLu/CjCiDCI0grnvsdRsM.Skj8BlekviAtNlf.a0n/9kcFHnxj8QO", zip_code: "38103"}
# ])
