Image.create!([
  {listing_id: 1, url: "https://images.squarespace-cdn.com/content/v1/533b0402e4b00b17bef36c51/1410818881149-I9I8MK648RHYT0QFON8J/ke17ZwdGBToddI8pDm48kOP4k6nJKwU86sL92UkQqe5Zw-zPPgdn4jUwVcJE1ZvWQUxwkmyExglNqGp0IvTJZamWLI2zvYWH8K3-s_4yszcp2ryTI0HqTOaaUohrI8PIo5fmh4JP_kiV1wIZN080qp3QoXl2SfsMhkQGk2guP8IKMshLAGzx4R3EDFOm1kBS/141754491-L-3.jpg"},
  {listing_id: 1, url: "https://www.louisianasportsman.com/wp-content/uploads/2014/01/p1391188684-1.jpg"},
  {listing_id: 2, url: "https://content.osgnetworks.tv/wildfowl/content/photos/mallard-drake-landing-on-water.jpg"},
  {listing_id: 2, url: "https://mossyoak-cezjaqp1wr.netdna-ssl.com/sites/default/files/inline-images/Duck%20Hunt_0.jpg"},
  {listing_id: 3, url: "http://mdwfp.com/media/257858/duck-hunter.jpg"},
  {listing_id: 3, url: "https://www.outdoorproperties.com/wp-content/uploads/2014/03/1110.jpg"},
  {listing_id: 4, url: "https://d138cv3no7lm06.cloudfront.net/sites/default/files/inline-images/DuckHuntingMississippieDelta_1.jpg"},
  {listing_id: 4, url: "https://www.mdwfp.com/media/254344/ducks-1.jpg?width=500&height=374.2857142857143"}
])
Listing.create!([
  {user_id: 1, title: "740 Acres in Parkin, AR", description: "There is a 4 day reservation during Christmas Week, December 20-23, 2021. This is primarily rice field hunting, with some fields in beans this year. There are 4 pit blinds to hunt that will all be available. There is an available guide service upon request, but only for the first 3 days (not available December 23). Unfortunately, we will not be able to split this into individual days, so it's 4 days or bust! Contact Will Petty below for more information!", address: "774 State HWY 306, Parkin, AR 72373", latitude: nil, longitude: nil, availability: "December 20-23, 2021", price: "1200"},
  {user_id: 1, title: "Weekend Leases Available in Cherry Valley, AR", description: "Convallis posuere morbi leo urna molestie. Vel quam elementum pulvinar etiam non quam lacus. Varius duis at consectetur lorem donec massa. Amet cursus sit amet dictum sit amet. Penatibus et magnis dis parturient montes. Pellentesque elit eget gravida cum.", address: "3509 AR-1, Cherry Valley, AR 72324", latitude: nil, longitude: nil, availability: "Dec 11-12, 2021, Dec 18-19, 2021 Jan 1-2, 2022, Jan 7-8, 2022", price: "$250/day, $450/weekend"},
  {user_id: 2, title: "Weekend & Weekday Leases Available in Parkin, AR", description: "Vulputate eu scelerisque felis imperdiet proin fermentum leo. Neque vitae tempus quam pellentesque nec nam aliquam sem. Ornare quam viverra orci sagittis eu. Semper eget duis at tellus. Cursus in hac habitasse platea dictumst quisque sagittis. Vestibulum lectus mauris ultrices eros in. Amet aliquam id diam maecenas ultricies.", address: "265 State HWY 422, Parkin, AR 72373", latitude: nil, longitude: nil, availability: "Dec 11-12, 2021, Dec 21-23, 2021 Jan 1-7, 2022", price: "$275/day, 5 or more days $225/day"},
  {user_id: 2, title: "Full Season Lease Available in Earle, AR", description: "Tempus imperdiet nulla malesuada pellentesque. Nec tincidunt praesent semper feugiat. Non nisi est sit amet facilisis magna etiam tempor orci. Proin nibh nisl condimentum id venenatis. Tristique senectus et netus et malesuada fames. Cursus eget nunc scelerisque viverra mauris in aliquam sem fringilla.", address: "261 Twist HWY, Earle, AR 72331", latitude: nil, longitude: nil, availability: "Sept 15-30, Nov 21-30, Dec 11-23, 2021, Dec 26, 2021 - Jan 31, 2022", price: "$8000, one field, no splitting the leases between multiple groups"}
])
User.create!([
  {first_name: "Bill", last_name: "Shelby", email: "bill@gmail.com", phone_number: "5555555555", address: "1900 York Ave", city: "Memphis", state: "TN", about_me: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ipsum suspendisse ultrices gravida dictum. Vestibulum morbi blandit cursus risus at ultrices. Bibendum at varius vel pharetra vel turpis nunc eget. Ornare arcu dui vivamus arcu felis bibendum ut tristique et.", image_url: "https://www.fillmurray.com/640/360", host: true, password_digest: "$2a$12$6.xyvMR6tZzBq.EdL82IgeKPhD7ysdNa06AVlKDe.UTArt9VH4Cai", zip_code: "38104"},
  {first_name: "Bentley", last_name: "Merganser", email: "bentley@gmail.com", phone_number: "5555555555", address: "1123 Harbor Bend Cv", city: "Memphis", state: "TN", about_me: "In aliquam sem fringilla ut morbi tincidunt augue interdum velit. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Duis ultricies lacus sed turpis tincidunt id. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Massa tempor nec feugiat nisl pretium fusce.", image_url: "https://www.placecage.com/640/360", host: false, password_digest: "$2a$12$ktYfBg2nz8ZvUXNEaxs.1uVUtkTCX6BRoK2I8mtVZZJOzmo4lhF/W", zip_code: "38103"},
  {first_name: "Evan", last_name: "Mallard", email: "evan@gmail.com", phone_number: "5555555555", address: "1154 Harbor River Cv", city: "Memphis", state: "TN", about_me: "Etiam sit amet nisl purus in mollis nunc sed id. Aenean euismod elementum nisi quis eleifend quam. Dolor morbi non arcu risus quis. Montes nascetur ridiculus mus mauris vitae ultricies leo. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Volutpat ac tincidunt vitae semper quis lectus.", image_url: "https://www.stevensegallery.com/640/360", host: false, password_digest: "$2a$12$ZPbry9HHyZRb8FunqAxKBOQnAMqfNvMcnrU33px249yrS3xQ2BhTG", zip_code: "38103"},
  {first_name: "William", last_name: "Petty", email: "pettwil1131@gmail.com", phone_number: "5555555555", address: "1131 Harbor River Cv", city: "Memphis", state: "TN", about_me: "Hey I'm Will. I live in Memphis, TN and I enjoy duck hunting, fishing, golf, and gardening.", image_url: "https://avatars.githubusercontent.com/u/77342332?v=4", host: true, password_digest: "$2a$12$pzyRCj3yUsPEMV9emcUtRe7qHQgP3ivmMNr5XbA0Ifo6mXBwLBfIq", zip_code: "38103"}
])
